{{< include macros.qmd >}}

# Applications of magnetostatics {#sec-applications-magnetostatics}

Having introduced the basic concepts for magnetostatics, let's now put them into practice to better understand magnetism.

## Surface currents

::: {#.callout-warning}

Add section on surface currents

::: 

## Magnetic monopoles

Let's start by looking more carefully at the Gauss' law for magnetic fields:

$$\nabla \cdot \bfB = 0.$$

What this equation tells us, physically, is that there is no such thing as a _magnetic point charge_ (more commonly known as a _monopole_). To see this, let's compare it with Gauss' law for electric fields:

$$\nabla \cdot \bfE = \frac{\rho}{\epsilon_0}.$$

In this case, the point charges (or _electric monopoles_, to continue the parallelism) are the sources and sinks of electric field. Therefore, going back to the magnetic field equation, we conclude magnetic monopoles can't exist.

Mathematically it might still make sense to allow for magnetic monopoles, and from a physical point of view they also are a useful tool to understand some effects (especially going down to quantum mechanics). However, no one has ever been able to observe a magnetic monopole in real life, so one should not worry very much about them.

## Magnetic dipoles {#sec-magnetic-dipoles}

Now let's talk about magnetic dipoles. Consider the magnetic vector potential generated by a current $I$ flowing through a small circle $C$. From @eq-vector-potential, we have

$$ \bfA (\bfr) = \frac{\mu_0 I}{4 \pi} \int_C \frac{\dd \bfr'}{|\bfr - \bfr'|}.$$

We now want to see what happens when we make this circle infinitely small. Wlog we take the $C$ to be centred at the origin and lying on the $(x,y)$-plane. We can then parameterise it as $\bfr' = (R \cos \theta', R \sin \theta', 0)$ for $\theta' \in [0, 2\pi)$, where $R > 0$ is the radius of the circle. If we take a Taylor expansion in the limit of $R \ll 1$, we can write the integrand as

$$ \frac{1}{|\bfr - \bfr'|} = \frac{1}{\sqrt{(x - R \cos \theta')^2 + (y - R \sin \theta')^2 + z^2}} = \frac{1}{\sqrt{x^2 + y^2 + z^2}} + R \frac{x \cos \theta' + y \sin \theta'}{\left(x^2 + y^2 + z^2 \right)^\frac{3}{2}} + O(R^2).$$

Using that $\dd \bfr' = (-R \sin \theta',- R \cos \theta', 0) \dd \theta'$, we can write the vector potential as 

$$
\begin{aligned}
\bfA (\bfr) &= \frac{\mu_0 I}{4 \pi} \int_C \left(\frac{1}{\sqrt{(x - R \cos \theta')^2 + (y - R \sin \theta')^2 + z^2}} \right) \dd \bfr' \\
&= \frac{\mu_0 I}{4 \pi} \int_0^{2\pi} \left[\frac{1}{\sqrt{x^2 + y^2 + z^2}} + R \frac{x \cos \theta' + y \sin \theta'}{\left(x^2 + y^2 + z^2 \right)^\frac{3}{2}} + O(R^2) \right] (-R \sin \theta',- R \cos \theta', 0) \dd \theta'\\
&= \frac{\mu_0 I}{4 \pi r^3} \left[\pi R^2 (-y, x, 0) + O(R^2) \right]\\
&= \frac{\mu_0 I}{4 \pi r^3} \left[\pi R^2 \bfe_z \times \bfr + O(R^2) \right]
\end{aligned}
$$ {#eq-vector-potential-magnetic-dipole-derivation}

The first term in the integral vanishes, as the integral is with respect to the tilde variables. Therefore, we are effectively taking the integral of a constant over a closed curve. In the last line we have just rewritten the result as a cross product for convenience.

Continuing with rewriting things in a convenient way, let's introduce the _magnetic dipole moment_:

$$\bfm = I \pi R^2 \bfn,$$

where $\bfn$ is the vector normal to the surface enclosed by $C$ (in our calculations above we have $\bfn = \bfe_z$ due to our choice of coordinates). Now let's take the limit $\bfR \to 0$ while taking $I \to \infty$ in such a way that $I \pi R^2$ remains constant. THen, as the higher order terms vanish, the potential @eq-vector-potential-magnetic-dipole-derivation can be written as

$$\bfA (\bfr) = \frac{\mu_0}{4 \pi} \frac{\bfm \times \bfr}{|\bfr|^3}.$$ {#eq-vector-potential-magnetic-dipole}

Calculating the magnetic field of the dipole we obtain, after some algebra,

$$\bfB(\bfr) = \nabla \times \bfA (\bfr) = \frac{\mu_0}{4 \pi} \left(- \frac{\bfm}{|\bfr|^3} + \frac{3 (\bfm \cdot \bfr) \bfr}{|\bfr|^5}\right).$$ {#eq-B-dipole}

## Magnetic forces

Now let's turn our attention to magnetic forces. We will consider two cases: forces between currents and forces between dipoles.

### Force between currents

We first consider the force between two current distributions $\bfJ_1(\bfr)$ and $\bfJ_2 (\bfr)$ defined in $\Omega_1$ and $\Omega_2$, respectively. Take the magnetic field produced by $\bfJ_1$, from the Biot-Savart law (@def-Biot-Savart-law) we have

$$\bfB(\bfr) = \frac{\mu_0}{4 \pi} \int_{\Omega_1} \frac{\bfJ_1(\bfr') \times (\bfr - \bfr')}{|\bfr - \bfr'|^3} \dd V'.$$

I we restrict ourselves to the case where we have a current $I_1$ through a curve (wire) $C_1$, we can write it as

$$\bfB(\bfr) = \frac{\mu_0 I_1}{4 \pi} \int_{C_1} \frac{\dd \bfr_1 \times (\bfr - \bfr_1)}{|\bfr -\bfr_1|^3}.$$

Now let's bring in the current distribution $\bfJ_2$, which will experience a force due to $\bfJ_1$ of

$$\bfF =\int_{\Omega_2} \bfJ_2 (\bfr) \times \bfB(\bfr) \dd V,$$

or, if we again restrict to the case where we have a current $I_2$ through a curve $C_2$,

$$\bfF = I_2 \int_{C_2} \dd \bfr \times \bfB(\bfr).$$

Combining the two results we obtain

$$\bfF = \frac{\mu_0}{4\pi} I_1 I_2 \int_{C_1} \int_{C_2} \dd \bfr_2 \times \left( \dd \bfr_1 \times \frac{\bfr_2 - \bfr_1}{| \bfr_2 - \bfr_1|^3} \right).$$ {#eq-force-between-currents}

Notice the symmetry of the expression: if we were to compute the force on $\bfJ_1$ produced by $\bfJ_2$ we would reach the same result.

::: {#exm-two-wires}

## Two straight wires

Consider the case were we have to infinite, straight, parallel wires a distance $d$ from each other, carrying currents $I_1$ and $I_2$ respectively. We want the force applied to the second wire.

Wlog we can write $\bfr_1 = (0, 0, z_1)$ and $\bfr_2 = (d, 0, z_2)$, and derive that $\dd \bfr_1 = \dd z_1 \bfe_z$ and $\dd \bfr_2 = \dd z_2 \bfe_z$. Then, @eq-force-between-currents becomes

$$\bfF = \frac{\mu_0}{4 \pi} I_1 I_2 \int_{-\infty}^{\infty} \int_{-\infty}^{\infty} \bfe_z \times \left(\bfe_z \times \frac{\bfr_2 - \bfr_1}{|\bfr_2 - \bfr_1|^3}\right) \dd z_2 \dd z_1.$$

We have $\bfr_2 - \bfr_1 = d \bfe_x + (z_2 - z_1) \dd \bfe_z$, and using the properties of the cross product we obtain

$$\begin{aligned}
\bfF &= \frac{\mu_0}{4 \pi} I_1 I_2 \int_{-\infty}^{\infty} \int_{-\infty}^{\infty} \frac{-d \bfe_x}{\left(d^2 + (z_2 - z_1)^2\right)^\frac{3}{2}} \dd z_2 \dd z_1\\
&= - \frac{\mu_0}{2 \pi d} I_1 I_2 \int_{-\infty}^{\infty} \bfe_x \int_{-\infty}^{\infty} \dd z_2.
\end{aligned}$$

The second integral is infinite, which makes sense as it represents the length of the second wire. But if we consider only the force per unit length on the wire, we get

$$\bff = - \frac{\mu_0}{2 \pi d} I_1 I_2 \int_{-\infty}^{\infty} \bfe_x.$$

If the currents have the same sign (i.e. $I_1 I_2 > 0$), then the force is attractive, while if the currents have opposite sign it is repulsive.

:::

### Force between dipoles

Let's now calculate the force that a given magnetic field $\bfB$ exerts on a dipole. We will use the same argument that we used in the definition of the dipole (@sec-magnetic-dipoles), in which we took the current around an infinitely small circular wire. From the Lorentz force law (@def-Lorentz-force), the force on the dipole is

$$\bfF = \int_C I \dd \bfr' \times \bfB(\bfr').$$

Using the parameterisation $\bfr'=\left(R \cos \theta', R \sin \theta', 0 \right)$ for $\theta' \in [0, 2\pi)$, and taking the Taylor expansion in the limit of small $R$ we get

$$\begin{aligned}
\bfF &= I \int_0^{2\pi} \left(-R \sin \theta', R \cos \theta', 0 \right) \times \left[ \bfB(\bfzero) + \frac{\partial}{\partial x} \bfB(\bfzero) R \cos \theta' + \frac{\partial}{\partial y} \bfB(\bfzero) R \sin \theta' + O(R^2) \right] \dd \theta' \\
&= I \pi R^2 \left[ \bfe_y \times \frac{\partial}{\partial x} \bfB(\bfzero) - \bfe_x \times \frac{\partial}{\partial y} \bfB(\bfzero) + O(R^3) \right] \\
&= I \pi R^2 \left[ \frac{\partial}{\partial x} B_z(\bfzero) \bfe_x + \frac{\partial}{\partial y} B_z(\bfzero) \bfe_y - \left( \frac{\partial}{\partial x} B_x(\bfzero) + \frac{\partial}{\partial y} B_y(\bfzero) + O(R^3) \right)\right] \\
&= I \pi R^2 \left[\nabla B_z(\bfzero) - \left( \nabla \cdot \bfB(\bfzero) \right) \bfe_z + O(R^3) \right].
\end{aligned}$$

Taking the limit $R \to 0$ while keeping the dipole moment $\bfm = I \pi R^2 \bfe_z$ constant we obtain

$$\bfF = \nabla (\bfm \cdot \bfB) - (\nabla \cdot \bfB) \bfm = \nabla(\bfm \cdot \bfB) = \nabla (\bfm \cdot \bfB),$$ {#eq-force-on-dipole}

where in the final step we have used that $\nabla \cdot \bfB = 0$. 

This force is conservative, and we can define the potential

$$V_\text{dipole} = - \bfm \cdot \bfB, \quad \implies \quad \bfF = - \nabla V_\text{dipole}.$$

The torque around the origin (using @eq-triple-cross-product) is

$$ \bftau = \int_C \bfr' \times \left(I \dd \bfr' \times \bfB(\bfr') \right) = I \int_C \dd \bfr' \left( \bfr' \cdot \bfB(\bfr') \right).$$

By a similar argument as before, we can write

$$\begin{aligned}
\bftau &= I \int_0^{2\pi} \left( -R \sin \theta' , R \cos \theta', 0 \right) \left[ B_x(\bfzero) R \cos \theta' + B_y(\bfzero) R \sin \theta' + O(R^2) \right] \dd theta'\\
&= I \pi R^2 \left[ (- B_y(\bfzero), B_x(\bfzero), 0) + O(R) \right],
\end{aligned}$$

and taking the limit

$$\bftau = \bfm \times \bfB.$$

Note that both for the force and the forque, the expressions are analogous to those of the electric dipole, but replacing $\bfp$ with $\bfm$ and $\bfE$ with $\bfB$. This also implies that magnetic dipoles will try to align with the magnetic field.

::: {#exm-force-between-dipoles}

## Force between dipoles

Now let's consider the force between to dipoles with moment $\bfm_1$ and $\bfm_2$ separated by a distance $\bfd$ (with $|\bfd| = d$). The magnetic field produced by the first dipole is given by @eq-B-dipole. Then, using @eq-force-on-dipole we obtain that the force on the second dipole is

$$\bfF = \frac{\mu_0}{4\pi} \nabla \left( - \frac{\bfm_1 \cdot \bfm_2}{d^3} + \frac{3(\bfm_1 \cdot \bfd)(\bfm_2 \cdot \bfd)}{d^5} \right).$$

We can compute the explicit expression (note that, here, the gradient applies on the vector $\bfd$). After some careful^[And painful!] manipulation, we obtain

$$\bfF = \frac{3 \mu_0}{4 \pi d^4} \left( (\bfm_1 \cdot \hat{\bfd}) \bfm_2 + (\bfm_2 \cdot \hat{\bfd}) \bfm_1 + (\bfm_1 \cdot \bfm_2) \hat{\bfd} - 5 (\bfm_1 \cdot \hat{\bfd}) (\bfm_2 \cdot \hat{\bfd}) \hat{\bfd}  \right),$$

where $\hat{\bfd} = \bfd / d$ is the unit vector pointing from $\bfm_1$ to $\bfm_2$.


:::



## Application: permanent magnets

All the discussion we have had up to now was about magnetic fields arising from electric currents. But the magnets we are familiar with are the kind of thing we buy on our holidays to stick on our fridges. So where are the currents that produce the magnetic field in those magnets?

The answer to this question involves quantum mechanics. Even though quantum mechanics is out of scope for this model, let's try to give some intuition about it. 

![Diagram of the magnetic field produced by a bar (or straight) magnet. Left: iron fillings. Centre: field lines. Right: representation as compass needles. <a href="https://commons.wikimedia.org/wiki/File:VFPt_cylindermagnet_field-representations.svg">Geek3</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>, via Wikimedia Commons.](./figs/magnet.svg){#fig-magnet}

The magnetism of such materials arises from the _spin_ of the electrons. Electrons have an inherent angular momentum called spin. If you picture the electrons like tiny spheres you can imagine the spin in the same way as the Earth's spin^[As you probably know electrons are a lot more complicated in real life, so this analogy only will take us thus far.]. It is this spin that produces a magnetic field. Typically, these magnetic fields point in all directions so their contributions basically cancel out at the macroscopic scale. However, when the spins of these many (many!) electrons align, the material produces a noticeable magnetic field.

