{{< include macros.qmd >}}

# Electrodynamics {#sec-electrodynamics}

Up to now, we only considered static situations. We could already infer from the stationary Maxwell's equations that there are some connections between electric and magnetic fields: they are both produced by electric charges, the former by their existence, the latter by their motion.

However, the interaction between electric and magnetic fields is much deeper, and this is only apparent when we let them change in time. This is the focus of this chapter.

## Faraday's Law of Induction

Let's first consider how @eq-curl-E-zero is modified when we allow both $\bfE$ and $\bfB$ to change in time. This is given by the Faraday's law^[Named after Michael Faraday (1791-1867) the English chemist and physicist. He actually started the Royal Institution Christmas Lectures, which still carry on today. You can watch past lectures at the [Royal Institution website](https://www.rigb.org/christmas-lectures)].

::: {#thm-Faraday-law}

## Faraday's law

The relationship between the electric field $\bfE$ and the magnetic field $\bfB$ is given by

$$ \nabla \times \bfE = - \frac{\partial \bfB}{\partial t} $$

:::

::: {.proof}

This is not an actual proof, but we will show it for a particular case to get the idea. Generalising the proof is much trickier and out of the scope of this module.

Consider the electric and magnetic fields generated by a set of charges moving with constant velocity $\bfv$ (i.e. moving along a straight line with constant speed). By the Lorentz force law (@def-Lorentz-force), an observer that is not moving will measure a following force over a charge $q$:

$$ \bfF = q \bfE + q \bfv \times \bfB .$$

Now consider an observer moving with the same constant velocity $\bfv$ as the charges. To that observer, the charges will look static and thus will only produce an electric field $\bfE'$. They will measure a force over a charge $q$

$$ \bfF' = q \bfE'.$$

Now since we assume the two observer should be measuring the same force^[Things get trickier in the relativistic world.] we must have

$$ \bfE' = \bfE + \bfv \times \bfB. $$

For the second observer, the electric field is static, so @eq-curl-E-zero applies. Then

$$ 
\begin{aligned}
\bfzero = \nabla \times \bfE' &= \nabla \times \bfE + \nabla \times \left( \nabla \times \bfB \right)\\
&= \nabla \times \bfE + \bfv (\nabla \cdot \bfB) - (\bfv \cdot \nabla) \bfB \\
&= \nabla \times \bfE - (\bfv \cdot \nabla) \bfB,
\end{aligned}
$$ {#eq-aux-Faraday-law}

where in the second line we have used `CROSSREF` and in the third line we have applied @thm-Gauss-law-magnetism.

For the first observer (the static one) all charges move with constant velocity $\bfv$, so the magnetic field at position $\bfr + \bfv \tau$ and time $\tau$ is the same as the magnetic field at position $\bfr$ and time $t$:

$$\bfB \left(\bfr + \bfv \tau, t + \tau \right) = \bfB(\bfr,t).$$

This is true for all $\tau$, so we can divide by $\tau$ and take the limit $\tau \to 0$, obtaining^[We are omitting the details here, but this is the definition of the total derivation, widely used in physics, which account for the intrinsic change of $\bfB$ in time (first term) and the change in time due to the motion in space (second term).]

$$ \frac{\partial \bfB}{\partial t} + \left(\bfv \cdot \nabla \right) \bfB = \bfzero.$$

Substituting this back into @eq-aux-Faraday-law we obtain

$$ \nabla \times \bfE = - \frac{\partial \bfB}{\partial t}.$$

::: 

::: {#cor-Faraday-law}

For any simple closed curve $C = \partial \Sigma$ bounding a fixed surface $\Sigma$, the Faraday law can be rewritten as

$$ \int_C \bfE \cdot \dd \bfr = - \frac{\dd}{\dd t} \int_\Sigma \bfB \cdot \bfn \; \dd A.$$ 

:::

Let's now introduce a couple of useful definitions.

::: {#def-magnetic-flux}

## Magnetic flux

The integral $\Phi = \int_\Sigma \bfB \cdot \bfn \dd A$ is called the magnetic flux through $\Sigma$.

:::

::: {#def-emf}

## Electromotive force (emf)

The integral $\mathcal{E}_\mathrm{emf} = \int_C \bfE \cdot \dd \bfr$ is called the electromotive force.^[Not confusingly at all, the electromotive force is not actually a force. It is the tangential component of the force per unit charge integrated along $C$.]

:::

Then, Faraday's law can be rewritten as

$$ \mathcal{E}_\mathrm{emf} = - \frac{\dd \Phi}{\dd t}.$$

This is simply a change in notation, but you may encounter this form in books.

Faraday's law tells us that if we change the magnetic flux through $\Sigma$ then we will induce a current. There are multiple ways of doing so physically. For example, one could change the magnetic field (e.g. by moving a magnet around) or maybe change the surface $\Sigma$ (e.g. by moving the wires enclosing it). There is another effect though. When a current flows in a wire, it will create its own magnetic field that will oppose the change that has induced the current in the first place. This is called _Lenz's law_. 

We can illustrate it as follows:

$$ \text{change in } \bfB \xrightarrow[]{\text{Faraday}} \bfE \xrightarrow[]{\text{Lorentz}} \text{current} \xrightarrow[]{\text{Ampère}} \bfB.$$  


::: {.callout-warning}

Consider adding


- Magnetostatic energy

- Inductance

- Resistance


:::


## Displacement current

The last step before being able to write the Maxwell's equations is to revise Ampère's law (@thm-Ampere-law) to account for time-dependent electric fields. To do this, let's start with its integral form (@cor-Ampere-law-alternative):

$$ \int_C \bfB \cdot \dd \bfr = \mu_0 \int_\Sigma \bfJ \cdot \bfn \dd A.$$

Remember that $C$ is a simple closed curve bounding $\Sigma$. But there are infinitely many surfaces bounded by $C$, so let's consider another surface $\Sigma'$ such that $\partial \Sigma ' = C$. Then

$$0 = \int_\Sigma \bfJ \cdot \bfn \dd A - \int_{\Sigma'} \bfJ \cdot \bfn \dd A = \int_S \bfJ \cdot \bfn \dd A,$$ {#eq-flux-closed-surf}

where $S = \Sigma \cup \Sigma'$ is a closed surface. This tells us that the flux of $\bfJ$ through any closed surface must be zero. Another way of looking at this is to consider the volume $\Omega$ enclosed by $S$ (i.e. $\partial \Omega = S$). Then, we can write

$$\int_S \bfJ \cdot \bfn \; \dd A = \int_\Omega \nabla \cdot \bfJ \dd V = 0,$$

where we have applied the divergence theorem in the first equality and the steady current condition (@eq-conservation-current-steady). But let's now drop the static assumption. In that case, we need to use @eq-continuity instead, so

$$\begin{aligned}
\int_S \bfJ \cdot \bfn \; \dd A = \int_\Omega \nabla \cdot \bfJ \dd V &= - \int_\Omega \frac{\partial \rho}{\partial t} \dd V \\
&= - \epsilon_0 \int_\Omega \frac{\partial}{\partial t} \left( \nabla \cdot \bfE \right) \dd V \\
&= - \epsilon_0 \int_S \frac{\partial \bfE}{\partial t} \cdot \bfn \; \dd A \\
&= -\epsilon_0 \int_\Sigma \frac{\partial \bfE}{\partial t} \cdot \bfn \; \dd A + \epsilon_0 \int_{\Sigma'} \frac{\partial \bfE}{\partial t} \cdot \bfn \; \dd A,
\end{aligned}
$$

where we have used the continuity equation in the second line (@eq-continuity) and Gauss' law (@eq-Gauss-law-differential) in the third line, before applying the divergence theorem again and splitting the surface integral over $S$ back into $\Sigma$ and $\Sigma'$.

We conclude that

$$\int_\Sigma \left( \bfJ + \epsilon_0 \frac{\partial \bfE}{\partial t} \right) \cdot \bfn \; \dd A = \int_{\Sigma'} \left( \bfJ + \epsilon_0 \frac{\partial \bfE}{\partial t} \right) \cdot \bfn \; \dd A,$$

which suggests we can write Ampère's law @eq-Ampere-law as

$$ \nabla \times \bfB = \mu_0 \left( \bfJ + \epsilon_0 \frac{\partial \bfE}{\partial t}\right).$$

This is one of the Maxwell's equation (@eq-Maxwell-4). This extra term that we picked up, ${\partial \bfE}{\partial t}$, is called the _displacement current_.

There is a quite interesting historical note about this equation. While the other three Maxwell's equations (and the static version of Ampère's law) were discovered mostly through experiments (even though mathematicians were still needed to write them as equations), the displacement current term @eq-Maxwell-4 was discovered purely by reasoning by Maxwell, and that's probably why all four equations are now named after him. Moreover, the displacement current _must_ be included, otherwise the equations are not consistent, but we will discuss this in the next section.

## Maxwell's equations

So we have finally derived Maxwell's equations in their general form. We have Gauss' law for electric fields

$$\nabla \cdot \bfE = \frac{\rho}{\epsilon_0},$$ {#eq-Maxwell-1-bis}

and its equivalent for magnetic fields

$$\nabla \cdot \bfB = 0.$$ {#eq-Maxwell-3-bis}

We have not said anything about these equations in the time-dependent case, but it turns out they still hold (we just let $\bfE$, $\bfB$ and $\rho$ depend on time).

We have now introduced Faraday's law

$$\nabla \times \bfE = - \frac{\partial \bfB}{\partial t},$$ {#eq-Maxwell-2-bis}

and modified Ampère's law to account for time-dependent fields

$$\nabla \times \bfB = \mu_0 \left(\bfJ + \epsilon_0 \frac{\partial \bfE}{\partial t} \right).$$ {#eq-Maxwell-4-bis}

These four equations, jointly with the Lorentz force law

$$\bfF = q \left( \bfE + \bfu \times \bfB \right),$$

describe the whole of electromagnetism^[At least in the non-relativistic world.]. 

Let's took a closer look at the equations. The first two are scalar equations, while the latter two are vector equations. This means we have effectively 8 equations. Let's look at the unknowns now: each field has three components that we need to determine, so we have six unknowns in total. The system is overdetermined, so we should have two consistency conditions if we hope to get a solution.

First let's compute the time derivative of @eq-Maxwell-3-bis,

$$0 = \frac{\partial}{\partial t} \left( \nabla \cdot \bfB \right) = \nabla \cdot \left(\frac{\partial \bfB}{\partial t} \right) = - \nabla \cdot \left( \nabla \times \bfE \right),$$

which makes it consistent with @eq-Maxwell-2-bis.

The second condition is probably a lot more interesting. Let's now take the divergence of @eq-Maxwell-4-bis, which yields

$$0 = \nabla \cdot \left( \frac{1}{\mu_0} \nabla \times \bfB \right) = \nabla \cdot \bfJ + \epsilon_0 \frac{\partial}{\partial t} \left( \nabla \cdot \bfE \right) = \nabla \cdot \bfJ + \frac{\partial \rho}{\partial t},$$

where in the last step we have used @eq-Maxwell-1-bis. Therefore, the continuity equation is encapsulated in the Maxwell's equations. This means that we can only get a solution to the Maxwell's equation if $\rho$ and $\bfJ$ satisfy the continuity equation (they would not be physical otherwise). This is why the displacement current is necessary in @eq-Maxwell-4-bis.

## Light

We are now in a position to study what is probably one of the most astonishing outcomes of the Maxwell's equations: the governing equation for light. The Maxwell's equations tell us that the electric and magnetic fields are closely coupled together, and that oscillations on one affect the other.

Our starting point will be the Maxwell's equations in vacuum, that is assuming that there are no charges (i.e. $\rho = 0$ and $\bfJ = \bfzero$). To derive the equations governing the behaviour of light, let's start by taking the time derivative of @eq-Maxwell-4-bis:

$$ \mu_0 \epsilon_0 \frac{\partial^2 \bfE}{\partial t^2} = \frac{\partial}{\partial t} \left( \nabla \times \bfB \right) = \nabla \times \frac{\partial \bfB}{\partial t} = - \nabla \times \left( \nabla \times \bfE \right),$$

where, remember, we are assuming $\bfJ = \bfzero$. Now let's use the identity

$$\nabla \times \left( \nabla \times \bfE \right) = \nabla \left( \nabla \times \bfE \right) - \nabla^2 \bfE.$$

But by @eq-Maxwell-1-bis we conclude that the first term vanishes (remember, we assume $\rho = 0$), so we can write

$$\frac{1}{c^2} \frac{\partial^2 \bfE}{\partial t^2} - \nabla^2 \bfE = \bfzero,$$

where we defined

$$c \sqrt{\frac{1}{\mu_0 \epsilon_0}}.$$

Similarly, we can take the time derivative of @eq-Maxwell-2-bis to obtain

$$\frac{1}{c^2} \frac{\partial^2 \bfB}{\partial t^2} - \nabla^2 \bfB = \bfzero.$$

Therefore, both the electric and magnetic fields satisfy the wave equation^[If you are interested in learning more about waves, you should take [MA301 Waves and Metamaterials](https://warwick.ac.uk/fac/sci/maths/currentstudents/modules/ma301/)]. Let's look at the parameter $c$ we defined. Recall the values for the constants

$$\epsilon_0 \approx 8.854 \times 10^{-12} \; \mathrm{C}^2 \, \mathrm{N}^{-1} \, \mathrm{m}^{-2} \quad \text{and} \quad \mu_0 \approx 1.257 \times 10^{-6} \; \mathrm{N} \, \mathrm{A}^{-2},$$

so the value of $c$ is

$$c \approx 2.99 \times 10^{8} \; \mathrm{m}\,\mathrm{s}^{-1},$$

which is the speed of light!

- Polarisation

## Electromagnetic potentials and gauge transformations

We also need to think on how the introduction of the time dependency affects the electric and magnetic potentials we introduced in @def-electrostatic-potential and @def-magnetostatic-vector-potential.

Since @eq-Maxwell-3-bis still holds, we can define the magnetic potential $\bfA(\bfr, t)$ as

$$ \bfB = \nabla \times \bfA.$$ {#eq-B-potentials}

Using @eq-Maxwell-2-bis we obtain

$$0  = \nabla \times \bfE + \frac{\partial \bfB}{\partial t} = \nabla \times \left( \bfE + \frac{\partial \bfA}{\partial t} \right).$$

Therefore, we can introduce a scalar potential $\phi(\bfr, t)$ such that

$$\bfE + \frac{\partial \bfA}{\partial t} = - \nabla \phi.$$

Then, the electric field can be in terms of both potentials as

$$\bfE = - \nabla \phi - \frac{\partial \bfA}{\partial t}.$${#eq-E-potentials}

::: {#def-gauge-transformation-t}

## Gauge transformation

The transformations

$$ \bfA \rightarrow \bfA' = \bfA + \nabla \chi, \quad \text{and} \quad \phi \rightarrow \phi' = \phi - \frac{\partial \chi}{\partial t} $$

for any given function $\chi$ are called a _gauge transformations_. These can be seen as a generalisation of @def-gauge-transformation, and they leave @eq-B-potentials and @eq-E-potentials invariant.

:::

::: {#def-Lorenz-gauge}

## Lorenz gauge

The Lorenz^[Do not confuse Mr Ludvig Lorenz (1829-1891) with Mr Hendrik Lorentz (1853-1928).] gauge for $\bfA$ and $\phi$ is the condition

$$\frac{1}{c^2} \frac{\partial \phi}{\partial t} + \nabla \cdot \bfA = 0.$$

:::

This is analogous to the Coulomb gauge (@prp-Coulomb-gauge), and it will allow us to choose a form for $\chi$ so we can write @eq-B-potentials and @eq-E-potentials in a more convenient form.

::: {#thm-Maxwell-Lorenz-gauge}

In Lorenz gauge, Maxwell's equations can be written as

$$\frac{1}{c^2} \frac{\partial^2 \phi}{\partial t^2} - \nabla^2 \phi = \frac{\rho}{\epsilon_0},$$

$$\frac{1}{c^2} \frac{\partial^2 \bfA}{\partial t^2} - \nabla^2 \bfA = \mu_0 \bfJ.$$

:::

::: {.proof}

Taking @eq-Maxwell-1-bis and plugging in @eq-E-potentials,

$$ \frac{\rho}{\epsilon_0} = \nabla \cdot \bfE = \nabla \cdot \left( - \nabla \phi - \frac{\partial \bfA}{\partial t} \right) = - \nabla^2 \phi + \frac{1}{c^2} \frac{\partial^2 \phi}{\partial t},$$

where in the last step we have used the Lorenz gauge.

Similarly, taking @eq-Maxwell-4-bis and substituting @eq-B-potentials, we obtain

$$ \nabla \times \bfB = \nabla \left(\nabla \cdot \bfA \right) - \nabla^2 \bfA = \mu_0 \left[ \bfJ - \epsilon_0 \left( \frac{\partial}{\partial t} \nabla \phi + \frac{\partial^2 \bfA}{\partial t^2} \right) \right].$$

But from Lorenz gauge we have

$$\nabla \left( \nabla \cdot \bfA \right) = - \epsilon_0 \mu_0 \frac{\partial}{\partial t} \nabla \phi,$$

therefore we can write

$$-\nabla^2 \bfA + \frac{1}{c^2} \frac{\partial^2 \bfA}{\partial t^2} = \mu_0 \bfJ.$$

:::

## Electromagnetic energy and the Poynting vector

Electromagnetic waves carry energy. In fact, most of the energy we get in the Earth comes, in origin, from the light of the Sun. The aim of this section is to calculate this energy.

::: {#def-electromagnetic-energy-density}

## Electromagnetic energy density

The electromagnetic energy density for a given field is

$$\mathcal{E} = \frac{\epsilon}{2}\bfE \cdot \bfE + \frac{1}{2 \mu_0} \bfB \cdot \bfB.$$

:::

Do not confuse the electromagnetic energy density $\mathcal{E}$ with the electromotive force $\mathcal{E}_\mathrm{emf}$. In fact, the latter will not appear again in these notes.

::: {#thm-Poynting}

## Poynting's theorem

The electromagnetic energy density $\mathcal{E}$ satisfies

$$\frac{\partial \mathcal{E}}{\partial t} + \nabla \cdot \bfS = - \bfE \cdot \bfJ,$$ {#eq-Poynting}

where

$$\bfS = \frac{1}{\mu_0} \bfE \times \bfB,$$

is called the _Poynting vector_.

:::

::: {.proof}

From @def-electromagnetic-energy-density, taking the time derivative of the electromagnetic energy density we obtain

$$
\begin{aligned}
\frac{\partial \mathcal{E}}{\partial t} &= \epsilon_0 \bfE \cdot \frac{\partial \bfE}{\partial t} + \frac{1}{\mu_0} \bfB \cdot \frac{\partial \bfB}{\partial t}\\
&= \frac{1}{\mu_0} \bfE \cdot \left( \nabla \times \bfB - \mu_0 \bfJ \right) - \frac{1}{\mu_0} \bfB \cdot \left( \nabla \times \bfE \right) \\
&= - \nabla \cdot \left(\frac{1}{\mu_0} \bfE \times \bfB \right) - \bfE \cdot \bfJ,
\end{aligned}
$$

where in the second line we have used @eq-Maxwell-2-bis and @eq-Maxwell-4-bis, and the third line uses `CROSSREF`.

:::

Note that that @eq-Poynting is analogous to @eq-continuity. Therefore, one can continue the analogy, and say that the Poynting vector $\bfS$ is to the electromagnetic energy density $\mathcal{E}$, what the current density $\bfJ$ is to the charge density $\rho$. In other words, $\bfS$ is the flow of energy carried by the electromagnetic field. In the particular case where there are no currents, @eq-Poynting states that the electromagnetic energy is conserved. There is another interpretation of the Poynting vector though: it is the momentum stored in the electromagnetic field.
