{{< include macros.qmd >}}

# Preface {.unnumbered}

These are the lecture notes for the third-year Maths module [MA302 Electromagnetism](https://courses.warwick.ac.uk/modules/2025/MA302-15) taught at the [University of Warwick](https://warwick.ac.uk/). These notes are available both as a PDF and a static website (which should be suitable for screen-reading devices), you can access both at [https://brosaplanella.github.io/MA302-Electromagnetism/](https://brosaplanella.github.io/MA302-Electromagnetism/). I might update the notes as we go, fixing typos and improving explanations. You can keep track of those changes in the [CHANGELOG](https://github.com/brosaplanella/MA302-Electromagnetism/blob/main/CHANGELOG.md). Further material is available on Moodle for registered students.

These lectures notes, which aim to be self--contained, are inspired by three main sources:

1. D. Tong, [Electromagnetism](https://doi.org/10.1017/9781009594660), Cambridge University Press, Cambridge, 2025.
2. R.P. Feynman, R.B. Leighton, M.L. Sands, [The Feynman lectures on physics](https://www.feynmanlectures.caltech.edu/), Definitive ed, Pearson Addison Wesley, San Francisco, 2006.
3. Lecture notes of the B7.2 Electromagnetism course at the University of Oxford, written by James Sparks and Erik Panzer.

The first two are good references if you want to read more about the topic, probably Tong's book is closer in structure to these lecture notes. In both cases, they cover a lot more material than this module does.

## Aims and structure {#aims-and-structure}

The main aims of this module are:

- Provide the student with the background necessary to understand basic electromagnetism concepts and Maxwell's equations.
- Apply this knowledge to write and solve models for simple electromagnetism setups.
- Highlight the connections of electromagnetism to practical applications in our day-to-day lives.

We will look at electromagnetism from a mathematical perspective, and use it to better understand the world around us, which is what applied mathematics is about.

In @sec-introduction we will provide some motivation to the topic and recap some basic results from vector calculus that we will use in this module. 

We will start with electrostatics in @sec-electrostatics, which is the study of static electric charges. We will introduce some fundamental concepts like electric charge, electric field and electrostatic potential; and derive some results like Gauss' law. In @sec-applications-electrostatics we will put into practice what we learned about electrostatics, by developing some concepts further and using them to understand some real applications, like conductors or capacitors.

Next, we will turn our attention to magnetostatics (@sec-magnetostatics), which is the study of steady magnetic fields. As magnetic fields are produced by charges in motion, we will introduce the concepts of current and current density. We will also derive some key results, like the Biot-Savart law, Gauss'law for magnetism or Ampère's law. Similarly to electrostatics, in @sec-applications-magnetostatics we will focus on applications of magnetostatics.

In @sec-electrodynamics we will bring time into the equation, and generalise our previous results to allow for time-dependence, leading to the Maxwell's equations. We will talk about induction and displacement currents, but the spotlight will be on light^[Pun intended.]. We will derive the governing equation for electromagnetic waves, and introduce some results, though if you want to learn a lot more about wave you should probably sign up for [MA301 Waves and Metamaterials](https://warwick.ac.uk/fac/sci/maths/currentstudents/modules/ma301/).

We will conclude with @sec-matter, in which we will extend the Maxwell's equations to account for real macroscale materials, rather than just charges in motion, and explain some of the phenomena that arise.

This is the first time I teach this module, and there will doubtless be errors and typos in these notes. There are also probably sections that could be better explained. If you spot
anything or you have any suggestions, please do let me know via email.

[Dr Ferran Brosa Planella](https://www.brosaplanella.xyz), Summer 2025